# Generated by Django 5.0.7 on 2024-07-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='createdBy',
        ),
    ]
